### ISSUE TITLE
Chrome shows plain text

### ISSUE THREAD

**Issue by tanmuhittin** [RoumenDamianoff/laravel-feed#38]
In order chrome to recognize the xml in Feed.php file you can update

return Response::make(View::make($this->getView($format), $viewData), 200, array('Content-type' => $this->ctype.'; charset='.$this->charset))->header('Content-Type', 'text/xml');
 and
return Response::make(Cache::get($this->cacheKey), 200, array('Content-type' => $this->ctype.'; charset='.$this->charset))->header('Content-Type', 'text/xml');

thanks to http://blog.kongnir.com/2014/06/27/getting-laravel-to-return-a-view-as-rss-or-xml/

**Comment by RoumenDamianoff** [comment]
In the next version you will be able to set custom content-type values like 'text/xml' for your feeds so you could get exactly the same result (but this is not the correct content-type and there may be some problems with 3th party readers).

Chrome doesn't have native support for rss feeds by design. You can use [this extension](https://chrome.google.com/extensions/detail/nlbjncdgjeocebhnmkbbbdekmmmcbfjd) (made by Google itself) or another one to view rss feeds.

**Comment by mansouralex** [comment]
I'm setting the content-type as 'text/xml' using ` $feed->ctype = "text/xml";` 

but sometimes it renders as plain text.

**Comment by RoumenDamianoff** [comment]
Hi, could you give me an example for this, is this happening only with Chrome?

**Comment by mansouralex** [comment]
Please find the following two examples.

![screenshot-social-media-feed-l5 dev 2016-02-07 16-23-17](https://cloud.githubusercontent.com/assets/6759585/12872861/6da4c1b0-cdb7-11e5-9bf0-0c1d50e4ea10.png)
![screenshot-social-media-feed-l5 dev 2016-02-07 16-23-08](https://cloud.githubusercontent.com/assets/6759585/12872862/6dac7ffe-cdb7-11e5-8b36-1678aebbf416.png)

And I have only tried it with Chrome.

**Comment by RoumenDamianoff** [comment]
I see missing ```<![CDATA[ ]]>``` on description tag with one ``>`` breaking the document. You maybe use older version with broken views or custom view where you removed CDATA tag but forgot this ``>`` before ``</description>`` (in rss.blade.php on row 6). 

If you don't have [this extension](https://chrome.google.com/extensions/detail/nlbjncdgjeocebhnmkbbbdekmmmcbfjd) (made by Google) installed on Chrome, you may have problems all feeds, because this browser don't support any feeds by default and need additional plugin to work. Try to open this feed in Firefox, if it works there, but didn't work in Chrome you need to install this plugin. 

Also `text/xml` is not the default content-type for rss feeds its `application/rss+xml` for rss and `application/atom+xml` for atom, even if it works now with `text/xml` you still may have problems in the future with some 3th party apps.

Fix this and try again, but don't forget to clear your cache first (or don't use it while develop), because you may not see the changes, also don't forget to update or remove your views in ``resources/views/vendor/feed`` if you have any, because plugin update don't update them automatically but check this location first by default.

**Comment by mansouralex** [comment]
Thanks for your detailed answer. 

I have removed the custom view I had and used the one comes with the package,
and set the default content-type to `application/rss+xml `.

With chrome the result seems there is no difference, anyway using the extensions you are referring to  it's displaying just few items of the feed?

Have tried it with Firefox and it's working as expected. 

Thanks again.
